### ISSUE TITLE
AttributeError: 'module' object has no attribute 'popall'

### ISSUE THREAD

**Issue by Cactusolo** [neherlab/treetime_examples#6]
Hi ,
I have been using `TreeTime: Maximum Likelihood Phylodynamics tt 0.7.4`, with standard run `treetime --tree iqtree_alnclen.tre --aln subiqtree.fasta --dates date_iqtree.csv`. It was all good, but giving error as half-way. 

The error msg is **"AttributeError: 'module' object has no attribute 'popall'"** as detailes, below. Any suggestions are appreciated.

Symmetrized rates from j->i (W_ij):
  A C G T -
  A 0 0.4601  1.8243  0.6456  7.8015
  C 0.4601  0 0.3286  3.7665  8.3047
  G 1.8243  0.3286  0 0.6436  6.2111
  T 0.6456  3.7665  0.6436  0 7.3774
  - 7.8015  8.3047  6.2111  7.3774  0

Actual rates from j->i (Q_ij):
  A C G T -
  A 0 0.1361  0.5396  0.191 2.3074
  C 0.0819  0 0.0585  0.6703  1.4779
  G 0.3503  0.0631  0 0.1236  1.1927
  T 0.2094  1.2216  0.2087  0 2.3927
  - 0.0774  0.0824  0.0616  0.0732  0

Inferred sequence evolution model (saved as 2020-04-01_treetime/molecular_clock.txt):
Root-Tip-Regression:
 --rate:  9.280e-04
 --r^2:   0.32

/home/.local/lib/python2.7/site-packages/matplotlib/colors.py:680: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  not cbook.is_string_like(colors[0]):
/home/.local/lib/python2.7/site-packages/matplotlib/lines.py:44: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if is_string_like(style) and is_hashable(style):
/home/.local/lib/python2.7/site-packages/matplotlib/font_manager.py:971: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if is_string_like(family):
/home/.local/lib/python2.7/site-packages/matplotlib/font_manager.py:697: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if is_string_like(family):
/home/.local/lib/python2.7/site-packages/matplotlib/text.py:218: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  elif is_string_like(fontproperties):
Traceback (most recent call last):
  File "/usr/local/bin/treetime", line 12, in <module>
    return_code = params.func(params)
  File "/usr/local/lib/python2.7/dist-packages/treetime/argument_parser.py", line 213, in toplevel
    timetree(params)
  File "/usr/local/lib/python2.7/dist-packages/treetime/wrappers.py", line 607, in timetree
    confidence=0.9 if calc_confidence else None)
  File "/usr/local/lib/python2.7/dist-packages/treetime/treetime.py", line 829, in plot_vs_years
    ax = plt.subplot(111)
  File "/home/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1044, in subplot
    a = fig.add_subplot(*args, **kwargs)
  File "/home/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 1021, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/home/.local/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 73, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/home/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 529, in __init__
    self._init_axis()
  File "/home/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 622, in _init_axis
    self.xaxis = maxis.XAxis(self)
  File "/home/.local/lib/python2.7/site-packages/matplotlib/axis.py", line 676, in __init__
    self.cla()
  File "/home/.local/lib/python2.7/site-packages/matplotlib/axis.py", line 760, in cla
    self.reset_ticks()
  File "/home/.local/lib/python2.7/site-packages/matplotlib/axis.py", line 771, in reset_ticks
    cbook.popall(self.majorTicks)
**AttributeError: 'module' object has no attribute 'popall'**

Miao

**Comment by Cactusolo** [comment]
OK, it was resolved by `sudo apt-get install python-matplotlib`.
[In case others needed]
